export interface MarketDataEntry {
  zipCode: string;
  city: string;
  state: string;
  medianHomePrice: number;
  priceGrowthYoY: number;
  averageCapRate: number;
  vacancyRate: number;
  populationGrowth: number;
  employmentRate: number;
  medianHouseholdIncome: number;
  crimeIndex: number; // 0-100, lower is safer
  walkScore: number; // 0-100
  schoolRating: number; // 1-10
  demandScore: number; // 0-100
  supplyScore: number; // 0-100
  economicStrength: number; // 0-100
  rentGrowthYoY: number;
  daysOnMarket: number;
}

export const marketDatabase: MarketDataEntry[] = [
  {
    zipCode: '78701',
    city: 'Austin',
    state: 'TX',
    medianHomePrice: 650000,
    priceGrowthYoY: 8.2,
    averageCapRate: 6.5,
    vacancyRate: 4.8,
    populationGrowth: 3.2,
    employmentRate: 97.1,
    medianHouseholdIncome: 82000,
    crimeIndex: 38,
    walkScore: 85,
    schoolRating: 8,
    demandScore: 88,
    supplyScore: 62,
    economicStrength: 91,
    rentGrowthYoY: 6.8,
    daysOnMarket: 22,
  },
  {
    zipCode: '78702',
    city: 'Austin',
    state: 'TX',
    medianHomePrice: 580000,
    priceGrowthYoY: 9.5,
    averageCapRate: 7.2,
    vacancyRate: 5.2,
    populationGrowth: 4.1,
    employmentRate: 96.4,
    medianHouseholdIncome: 72000,
    crimeIndex: 45,
    walkScore: 78,
    schoolRating: 7,
    demandScore: 84,
    supplyScore: 58,
    economicStrength: 87,
    rentGrowthYoY: 7.5,
    daysOnMarket: 18,
  },
  {
    zipCode: '78704',
    city: 'Austin',
    state: 'TX',
    medianHomePrice: 720000,
    priceGrowthYoY: 7.1,
    averageCapRate: 5.9,
    vacancyRate: 4.2,
    populationGrowth: 2.8,
    employmentRate: 97.8,
    medianHouseholdIncome: 95000,
    crimeIndex: 32,
    walkScore: 88,
    schoolRating: 9,
    demandScore: 92,
    supplyScore: 55,
    economicStrength: 94,
    rentGrowthYoY: 5.9,
    daysOnMarket: 14,
  },
  {
    zipCode: '78745',
    city: 'Austin',
    state: 'TX',
    medianHomePrice: 420000,
    priceGrowthYoY: 11.2,
    averageCapRate: 7.8,
    vacancyRate: 6.1,
    populationGrowth: 5.4,
    employmentRate: 95.8,
    medianHouseholdIncome: 62000,
    crimeIndex: 52,
    walkScore: 65,
    schoolRating: 6,
    demandScore: 78,
    supplyScore: 70,
    economicStrength: 79,
    rentGrowthYoY: 9.2,
    daysOnMarket: 25,
  },
  {
    zipCode: '78753',
    city: 'Austin',
    state: 'TX',
    medianHomePrice: 380000,
    priceGrowthYoY: 12.8,
    averageCapRate: 8.5,
    vacancyRate: 7.2,
    populationGrowth: 6.1,
    employmentRate: 95.2,
    medianHouseholdIncome: 55000,
    crimeIndex: 61,
    walkScore: 55,
    schoolRating: 5,
    demandScore: 71,
    supplyScore: 75,
    economicStrength: 74,
    rentGrowthYoY: 10.1,
    daysOnMarket: 32,
  },
  {
    zipCode: '90210',
    city: 'Beverly Hills',
    state: 'CA',
    medianHomePrice: 3200000,
    priceGrowthYoY: 4.2,
    averageCapRate: 3.1,
    vacancyRate: 3.8,
    populationGrowth: 0.8,
    employmentRate: 97.2,
    medianHouseholdIncome: 185000,
    crimeIndex: 28,
    walkScore: 82,
    schoolRating: 10,
    demandScore: 95,
    supplyScore: 30,
    economicStrength: 96,
    rentGrowthYoY: 4.1,
    daysOnMarket: 45,
  },
  {
    zipCode: '10001',
    city: 'New York',
    state: 'NY',
    medianHomePrice: 1250000,
    priceGrowthYoY: 5.8,
    averageCapRate: 4.2,
    vacancyRate: 5.5,
    populationGrowth: 1.2,
    employmentRate: 96.1,
    medianHouseholdIncome: 105000,
    crimeIndex: 48,
    walkScore: 98,
    schoolRating: 7,
    demandScore: 90,
    supplyScore: 42,
    economicStrength: 92,
    rentGrowthYoY: 5.2,
    daysOnMarket: 28,
  },
  {
    zipCode: '60601',
    city: 'Chicago',
    state: 'IL',
    medianHomePrice: 485000,
    priceGrowthYoY: 6.4,
    averageCapRate: 6.8,
    vacancyRate: 7.8,
    populationGrowth: 0.5,
    employmentRate: 94.8,
    medianHouseholdIncome: 72000,
    crimeIndex: 65,
    walkScore: 88,
    schoolRating: 6,
    demandScore: 72,
    supplyScore: 68,
    economicStrength: 75,
    rentGrowthYoY: 5.8,
    daysOnMarket: 38,
  },
  {
    zipCode: '33101',
    city: 'Miami',
    state: 'FL',
    medianHomePrice: 620000,
    priceGrowthYoY: 14.2,
    averageCapRate: 5.8,
    vacancyRate: 5.8,
    populationGrowth: 4.8,
    employmentRate: 96.2,
    medianHouseholdIncome: 68000,
    crimeIndex: 58,
    walkScore: 72,
    schoolRating: 6,
    demandScore: 86,
    supplyScore: 65,
    economicStrength: 85,
    rentGrowthYoY: 12.4,
    daysOnMarket: 20,
  },
  {
    zipCode: '85001',
    city: 'Phoenix',
    state: 'AZ',
    medianHomePrice: 420000,
    priceGrowthYoY: 9.8,
    averageCapRate: 7.4,
    vacancyRate: 6.5,
    populationGrowth: 5.2,
    employmentRate: 96.0,
    medianHouseholdIncome: 62000,
    crimeIndex: 55,
    walkScore: 48,
    schoolRating: 6,
    demandScore: 80,
    supplyScore: 72,
    economicStrength: 80,
    rentGrowthYoY: 8.5,
    daysOnMarket: 28,
  },
  {
    zipCode: '30301',
    city: 'Atlanta',
    state: 'GA',
    medianHomePrice: 390000,
    priceGrowthYoY: 10.5,
    averageCapRate: 8.1,
    vacancyRate: 7.1,
    populationGrowth: 4.5,
    employmentRate: 95.5,
    medianHouseholdIncome: 65000,
    crimeIndex: 62,
    walkScore: 58,
    schoolRating: 5,
    demandScore: 77,
    supplyScore: 70,
    economicStrength: 78,
    rentGrowthYoY: 9.1,
    daysOnMarket: 24,
  },
  {
    zipCode: '98101',
    city: 'Seattle',
    state: 'WA',
    medianHomePrice: 850000,
    priceGrowthYoY: 7.5,
    averageCapRate: 4.9,
    vacancyRate: 5.4,
    populationGrowth: 2.8,
    employmentRate: 97.4,
    medianHouseholdIncome: 110000,
    crimeIndex: 42,
    walkScore: 92,
    schoolRating: 8,
    demandScore: 88,
    supplyScore: 48,
    economicStrength: 92,
    rentGrowthYoY: 6.8,
    daysOnMarket: 16,
  },
];

export const defaultMarketData: MarketDataEntry = {
  zipCode: 'default',
  city: 'National Average',
  state: 'US',
  medianHomePrice: 420000,
  priceGrowthYoY: 5.5,
  averageCapRate: 6.5,
  vacancyRate: 6.5,
  populationGrowth: 1.2,
  employmentRate: 96.0,
  medianHouseholdIncome: 70000,
  crimeIndex: 50,
  walkScore: 62,
  schoolRating: 6,
  demandScore: 70,
  supplyScore: 65,
  economicStrength: 72,
  rentGrowthYoY: 5.0,
  daysOnMarket: 35,
};

export function getMarketData(zipCode: string): MarketDataEntry {
  return marketDatabase.find((m) => m.zipCode === zipCode) || defaultMarketData;
}
