'use client';

import React from 'react';
import clsx from 'clsx';
import { CheckCircle2, AlertTriangle, Brain, TrendingUp, FileText, Target } from 'lucide-react';
import type { AIReport as AIReportType } from '@/types';

interface AIReportProps {
  report: AIReportType;
}

const recommendationConfig = {
  Buy: {
    bg: 'bg-green-500/10',
    border: 'border-green-500/40',
    text: 'text-green-400',
    badgeBg: 'bg-green-500',
    badgeText: 'text-white',
    glow: 'shadow-green-500/30',
    description: 'Strong investment opportunity. Proceed with due diligence.',
  },
  Hold: {
    bg: 'bg-yellow-500/10',
    border: 'border-yellow-500/40',
    text: 'text-yellow-400',
    badgeBg: 'bg-yellow-500',
    badgeText: 'text-black',
    glow: 'shadow-yellow-500/30',
    description: 'Acceptable but not compelling. Monitor for better entry.',
  },
  Pass: {
    bg: 'bg-red-500/10',
    border: 'border-red-500/40',
    text: 'text-red-400',
    badgeBg: 'bg-red-500',
    badgeText: 'text-white',
    glow: 'shadow-red-500/30',
    description: 'Risk/reward unfavorable at current terms. Seek better deals.',
  },
};

const sentimentColors = {
  positive: 'text-green-400 bg-green-500/10 border-green-500/20',
  neutral: 'text-blue-400 bg-blue-500/10 border-blue-500/20',
  negative: 'text-red-400 bg-red-500/10 border-red-500/20',
};

export default function AIReport({ report }: AIReportProps) {
  const recConfig = recommendationConfig[report.recommendation];

  return (
    <div className="space-y-6">
      {/* AI Header */}
      <div className="flex items-center gap-3 pb-4 border-b border-gray-200">
        <div className="p-2 bg-blue-500/10 rounded-xl">
          <Brain className="w-5 h-5 text-blue-400" />
        </div>
        <div>
          <h3 className="text-base font-semibold text-gray-900">AI Investment Report</h3>
          <div className="flex items-center gap-2 mt-0.5">
            <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
            <p className="text-xs text-gray-500">
              Confidence Score: {report.confidenceScore}% — Generated by Realytics AI
            </p>
          </div>
        </div>
      </div>

      {/* Recommendation Badge — TOP of report */}
      <div
        className={clsx(
          'flex items-center justify-between p-5 rounded-2xl border shadow-lg',
          recConfig.bg,
          recConfig.border,
          recConfig.glow
        )}
      >
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-wide font-medium mb-1">
            AI Recommendation
          </p>
          <div className="flex items-center gap-3">
            <Target className={clsx('w-6 h-6', recConfig.text)} />
            <span className={clsx('text-4xl font-extrabold tracking-tight', recConfig.text)}>
              {report.recommendation.toUpperCase()}
            </span>
          </div>
          <p className="text-sm text-gray-600 mt-2 max-w-sm">
            {recConfig.description}
          </p>
        </div>
        <div
          className={clsx(
            'w-20 h-20 rounded-2xl flex items-center justify-center text-3xl font-black shadow-lg flex-shrink-0',
            recConfig.badgeBg,
            recConfig.badgeText
          )}
        >
          {report.recommendation === 'Buy' ? '✓' : report.recommendation === 'Hold' ? '~' : '✗'}
        </div>
      </div>

      {/* Executive Summary */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <FileText className="w-4 h-4 text-blue-400" />
          <h4 className="text-sm font-semibold text-gray-900">Executive Summary</h4>
        </div>
        <p className="text-sm text-gray-700 leading-relaxed bg-gray-50 rounded-xl p-4 border border-gray-200">
          {report.executiveSummary}
        </p>
      </div>

      {/* Key Metrics */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <TrendingUp className="w-4 h-4 text-blue-400" />
          <h4 className="text-sm font-semibold text-gray-900">Key Metrics</h4>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {report.keyMetrics.map((metric) => (
            <div
              key={metric.label}
              className={clsx(
                'p-3 rounded-xl border text-center',
                sentimentColors[metric.sentiment]
              )}
            >
              <div className="text-xs text-gray-500 mb-1">{metric.label}</div>
              <div className={clsx('text-lg font-bold tabular-nums', sentimentColors[metric.sentiment].split(' ')[0])}>
                {metric.value}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Strengths & Risks Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* Strengths */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <CheckCircle2 className="w-4 h-4 text-green-400" />
            <h4 className="text-sm font-semibold text-gray-900">Strengths</h4>
            <span className="text-xs text-gray-400">({report.strengths.length})</span>
          </div>
          <div className="space-y-2">
            {report.strengths.map((strength, idx) => (
              <div
                key={idx}
                className="flex items-start gap-2.5 p-3 bg-green-500/5 border border-green-500/15 rounded-xl"
              >
                <CheckCircle2 className="w-4 h-4 text-green-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-gray-700 leading-relaxed">{strength}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Risks */}
        <div>
          <div className="flex items-center gap-2 mb-3">
            <AlertTriangle className="w-4 h-4 text-red-400" />
            <h4 className="text-sm font-semibold text-gray-900">Risks</h4>
            <span className="text-xs text-gray-400">({report.risks.length})</span>
          </div>
          <div className="space-y-2">
            {report.risks.map((risk, idx) => (
              <div
                key={idx}
                className="flex items-start gap-2.5 p-3 bg-red-500/5 border border-red-500/15 rounded-xl"
              >
                <AlertTriangle className="w-4 h-4 text-red-400 flex-shrink-0 mt-0.5" />
                <p className="text-xs text-gray-700 leading-relaxed">{risk}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Market Insights */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <TrendingUp className="w-4 h-4 text-purple-400" />
          <h4 className="text-sm font-semibold text-gray-900">Market Insights</h4>
        </div>
        <p className="text-sm text-gray-700 leading-relaxed bg-purple-500/5 rounded-xl p-4 border border-purple-500/15">
          {report.marketInsights}
        </p>
      </div>

      {/* Reasoning */}
      <div>
        <div className="flex items-center gap-2 mb-3">
          <Brain className="w-4 h-4 text-blue-400" />
          <h4 className="text-sm font-semibold text-gray-900">
            Why We Recommend: {report.recommendation}
          </h4>
        </div>
        <div className={clsx('p-4 rounded-xl border', recConfig.bg, recConfig.border)}>
          <p className="text-sm leading-relaxed text-gray-700">
            {report.reasoning}
          </p>
        </div>
      </div>

      {/* Disclaimer */}
      <p className="text-xs text-gray-400 text-center pt-2 border-t border-gray-200">
        This report is generated algorithmically for informational purposes only. It is not financial advice.
        Always consult a licensed real estate professional and perform independent due diligence before investing.
      </p>
    </div>
  );
}
